#!/usr/bin/env bash

cd vimpager
make install PREFIX=$HOME
cd ..

cd clang_complete
make install
make clean
cd ..

cd termstyle
python setup.py build
python setup.py install --user
cd ..

cd rednose
python setup.py build
python setup.py install --user
cd ..
